export const CURRICULUM = [
  {
    week_number: 1,
    title: 'Welcome to 3D Printing',
    objectives: [
      'Understand how FDM 3D printing works',
      'Identify all major Ender-2 printer parts',
      'Follow printer safety rules',
      'Complete your first print from a downloaded STL',
    ],
    lessons: [
      {
        title: 'How 3D Printing Works',
        estimated_minutes: 20,
        content_markdown: `## How 3D Printing Works\n\nFDM (Fused Deposition Modeling) printing works by melting plastic filament and depositing it layer by layer to build a 3D object.\n\n### Key concepts\n- **Filament** — the plastic material (we use PLA)\n- **Nozzle** — heats to ~200°C and melts the filament\n- **Build plate** — the surface your print sticks to\n- **Layers** — each pass of the nozzle adds one thin layer\n\n### Safety rules\n1. Never touch the nozzle while printing — it's very hot\n2. Print in a ventilated space\n3. Never leave the printer unattended for long prints\n4. Keep fingers away from moving parts`,
        videos: [{ title: 'Beginners Guide To 3D Printing In 2024', youtube_id: 'SejxOXdtOcg', youtube_url: 'https://youtu.be/SejxOXdtOcg' }],
        quiz: {
          id: 'seed-quiz-1-0',
          title: 'How 3D Printing Works',
          passing_score: 75,
          quiz_questions: [
            {
              id: 'seed-q-1-0-0',
              question_text: 'What does FDM stand for?',
              order_index: 0,
              quiz_options: [
                { id: 'seed-opt-1-0-0-0', option_text: 'Fused Deposition Modeling', is_correct: true },
                { id: 'seed-opt-1-0-0-1', option_text: 'Fixed Dimension Manufacturing', is_correct: false },
                { id: 'seed-opt-1-0-0-2', option_text: 'Filament Deposit Machine', is_correct: false },
                { id: 'seed-opt-1-0-0-3', option_text: 'Foam Delivery Method', is_correct: false },
              ],
            },
            {
              id: 'seed-q-1-0-1',
              question_text: 'What filament material do beginners typically use?',
              order_index: 1,
              quiz_options: [
                { id: 'seed-opt-1-0-1-0', option_text: 'PLA', is_correct: true },
                { id: 'seed-opt-1-0-1-1', option_text: 'ABS', is_correct: false },
                { id: 'seed-opt-1-0-1-2', option_text: 'PETG', is_correct: false },
                { id: 'seed-opt-1-0-1-3', option_text: 'Nylon', is_correct: false },
              ],
            },
            {
              id: 'seed-q-1-0-2',
              question_text: 'Approximately what temperature does the nozzle heat to?',
              order_index: 2,
              quiz_options: [
                { id: 'seed-opt-1-0-2-0', option_text: '200°C', is_correct: true },
                { id: 'seed-opt-1-0-2-1', option_text: '50°C', is_correct: false },
                { id: 'seed-opt-1-0-2-2', option_text: '350°C', is_correct: false },
                { id: 'seed-opt-1-0-2-3', option_text: '100°C', is_correct: false },
              ],
            },
            {
              id: 'seed-q-1-0-3',
              question_text: 'What is the build plate used for?',
              order_index: 3,
              quiz_options: [
                { id: 'seed-opt-1-0-3-0', option_text: 'The surface your print sticks to', is_correct: true },
                { id: 'seed-opt-1-0-3-1', option_text: 'Heating the filament', is_correct: false },
                { id: 'seed-opt-1-0-3-2', option_text: 'Controlling print speed', is_correct: false },
                { id: 'seed-opt-1-0-3-3', option_text: 'Storing the filament spool', is_correct: false },
              ],
            },
          ],
        },
      },
      {
        title: 'Printer Parts & Setup',
        estimated_minutes: 30,
        content_markdown: `## Know Your Printer\n\nLabel and understand each part of your Ender-2:\n\n| Part | Function |\n|------|----------|\n| Frame | Structural support |\n| X-axis gantry | Moves nozzle left/right |\n| Y-axis bed | Moves bed front/back |\n| Z-axis | Moves nozzle up/down |\n| Extruder | Feeds filament into hotend |\n| Hotend/nozzle | Melts and deposits filament |\n| Build plate | Surface for printing |\n| LCD screen | Control interface |\n\n### First steps\n1. Level the bed (4 corner knobs + center check)\n2. Load PLA filament\n3. Set temperature: nozzle 200°C, bed 60°C`,
        videos: [{ title: 'How To Level An Ender 3 Print Bed', youtube_id: 'duDopB4-QNg', youtube_url: 'https://youtu.be/duDopB4-QNg' }],
        quiz: {
          id: 'seed-quiz-1-1',
          title: 'Printer Parts & Setup',
          passing_score: 75,
          quiz_questions: [
            {
              id: 'seed-q-1-1-0',
              question_text: 'Which axis moves the nozzle left and right?',
              order_index: 0,
              quiz_options: [
                { id: 'seed-opt-1-1-0-0', option_text: 'X-axis gantry', is_correct: true },
                { id: 'seed-opt-1-1-0-1', option_text: 'Y-axis bed', is_correct: false },
                { id: 'seed-opt-1-1-0-2', option_text: 'Z-axis', is_correct: false },
                { id: 'seed-opt-1-1-0-3', option_text: 'Extruder', is_correct: false },
              ],
            },
            {
              id: 'seed-q-1-1-1',
              question_text: 'What does the extruder do?',
              order_index: 1,
              quiz_options: [
                { id: 'seed-opt-1-1-1-0', option_text: 'Feeds filament into the hotend', is_correct: true },
                { id: 'seed-opt-1-1-1-1', option_text: 'Heats the build plate', is_correct: false },
                { id: 'seed-opt-1-1-1-2', option_text: 'Controls the LCD menu', is_correct: false },
                { id: 'seed-opt-1-1-1-3', option_text: 'Moves the nozzle up and down', is_correct: false },
              ],
            },
            {
              id: 'seed-q-1-1-2',
              question_text: 'What temperature should the nozzle be set to for PLA?',
              order_index: 2,
              quiz_options: [
                { id: 'seed-opt-1-1-2-0', option_text: '200°C', is_correct: true },
                { id: 'seed-opt-1-1-2-1', option_text: '60°C', is_correct: false },
                { id: 'seed-opt-1-1-2-2', option_text: '100°C', is_correct: false },
                { id: 'seed-opt-1-1-2-3', option_text: '350°C', is_correct: false },
              ],
            },
            {
              id: 'seed-q-1-1-3',
              question_text: 'How many corner knobs are used to level the bed?',
              order_index: 3,
              quiz_options: [
                { id: 'seed-opt-1-1-3-0', option_text: '4', is_correct: true },
                { id: 'seed-opt-1-1-3-1', option_text: '2', is_correct: false },
                { id: 'seed-opt-1-1-3-2', option_text: '6', is_correct: false },
                { id: 'seed-opt-1-1-3-3', option_text: '8', is_correct: false },
              ],
            },
          ],
        },
      },
      {
        title: 'Your First Print',
        estimated_minutes: 45,
        content_markdown: `## Your First Print\n\nFor your first print, use the test file on the SD card that came with your printer.\n\n### Steps\n1. Insert the SD card\n2. On the LCD: *Print* → select the test file\n3. Watch the first layer carefully — it should be slightly squished\n4. If it's not sticking, pause and re-level\n5. Let it finish!\n\n### What to watch for\n- First layer adhesion (most important)\n- Stringing between parts\n- Layer lines (normal)\n\n### Homework\nWrite a Printer Journal entry: What surprised you? What went wrong? What do you want to make?`,
        videos: [{ title: 'How To Get The Perfect First Layer on Your 3D Prints', youtube_id: 'mXjTYDg-KNs', youtube_url: 'https://youtu.be/mXjTYDg-KNs' }],
        quiz: {
          id: 'seed-quiz-1-2',
          title: 'Your First Print',
          passing_score: 75,
          quiz_questions: [
            {
              id: 'seed-q-1-2-0',
              question_text: 'Where do you select the file to print on the Ender?',
              order_index: 0,
              quiz_options: [
                { id: 'seed-opt-1-2-0-0', option_text: 'On the LCD screen', is_correct: true },
                { id: 'seed-opt-1-2-0-1', option_text: 'In a phone app', is_correct: false },
                { id: 'seed-opt-1-2-0-2', option_text: 'On the extruder', is_correct: false },
                { id: 'seed-opt-1-2-0-3', option_text: 'On the build plate', is_correct: false },
              ],
            },
            {
              id: 'seed-q-1-2-1',
              question_text: 'What is the most important thing to watch during the start of a print?',
              order_index: 1,
              quiz_options: [
                { id: 'seed-opt-1-2-1-0', option_text: 'First layer adhesion', is_correct: true },
                { id: 'seed-opt-1-2-1-1', option_text: 'Print speed', is_correct: false },
                { id: 'seed-opt-1-2-1-2', option_text: 'Filament color', is_correct: false },
                { id: 'seed-opt-1-2-1-3', option_text: 'Room temperature', is_correct: false },
              ],
            },
            {
              id: 'seed-q-1-2-2',
              question_text: 'If your print is not sticking to the bed, what should you do?',
              order_index: 2,
              quiz_options: [
                { id: 'seed-opt-1-2-2-0', option_text: 'Pause and re-level the bed', is_correct: true },
                { id: 'seed-opt-1-2-2-1', option_text: 'Increase print speed', is_correct: false },
                { id: 'seed-opt-1-2-2-2', option_text: 'Turn off the printer immediately', is_correct: false },
                { id: 'seed-opt-1-2-2-3', option_text: 'Add more filament manually', is_correct: false },
              ],
            },
            {
              id: 'seed-q-1-2-3',
              question_text: 'What are "layer lines" on a finished print?',
              order_index: 3,
              quiz_options: [
                { id: 'seed-opt-1-2-3-0', option_text: 'Normal visible lines from each pass of the nozzle', is_correct: true },
                { id: 'seed-opt-1-2-3-1', option_text: 'Errors that mean the print failed', is_correct: false },
                { id: 'seed-opt-1-2-3-2', option_text: 'Lines drawn on the LCD screen', is_correct: false },
                { id: 'seed-opt-1-2-3-3', option_text: 'Marks left behind by supports', is_correct: false },
              ],
            },
          ],
        },
      },
    ],
    homework: { title: 'Printer Journal Entry', description: 'Write 1 paragraph about your first printing experience. What surprised you? What went wrong? What do you want to make next?', max_score: 10 },
  },
  {
    week_number: 2,
    title: 'TinkerCAD Basics',
    objectives: [
      'Create a free TinkerCAD account',
      'Navigate the 3D workspace (orbit, pan, zoom)',
      'Add, move, rotate, and scale basic shapes',
      'Use the align, group, and hole tools',
    ],
    lessons: [
      {
        title: 'Getting Started with TinkerCAD',
        estimated_minutes: 20,
        content_markdown: `## TinkerCAD Basics\n\nTinkerCAD is a free, browser-based 3D design tool by Autodesk.\n\n### Create your account\n1. Go to [tinkercad.com](https://tinkercad.com)\n2. Click *Sign up for free*\n3. Choose *Student* account (requires no email if under 13, but use your email for 13+)\n\n### Navigation controls\n| Action | How |\n|--------|-----|\n| Orbit | Right-click + drag |\n| Pan | Middle-click + drag |\n| Zoom | Scroll wheel |\n| Reset view | Press F |\n\n### Adding shapes\nDrag shapes from the right panel onto the workplane.`,
        videos: [{ title: 'TinkerCAD - Tutorial for Beginners in 10 MINS!', youtube_id: 'QIn9c5TjrKk', youtube_url: 'https://youtu.be/QIn9c5TjrKk' }],
        quiz: {
          id: 'seed-quiz-2-0',
          title: 'Getting Started with TinkerCAD',
          passing_score: 75,
          quiz_questions: [
            {
              id: 'seed-q-2-0-0',
              question_text: 'Who makes TinkerCAD?',
              order_index: 0,
              quiz_options: [
                { id: 'seed-opt-2-0-0-0', option_text: 'Autodesk', is_correct: true },
                { id: 'seed-opt-2-0-0-1', option_text: 'Adobe', is_correct: false },
                { id: 'seed-opt-2-0-0-2', option_text: 'Google', is_correct: false },
                { id: 'seed-opt-2-0-0-3', option_text: 'Microsoft', is_correct: false },
              ],
            },
            {
              id: 'seed-q-2-0-1',
              question_text: 'How do you orbit (rotate the view) in TinkerCAD?',
              order_index: 1,
              quiz_options: [
                { id: 'seed-opt-2-0-1-0', option_text: 'Right-click and drag', is_correct: true },
                { id: 'seed-opt-2-0-1-1', option_text: 'Left-click and drag', is_correct: false },
                { id: 'seed-opt-2-0-1-2', option_text: 'Middle-click and drag', is_correct: false },
                { id: 'seed-opt-2-0-1-3', option_text: 'Scroll wheel', is_correct: false },
              ],
            },
            {
              id: 'seed-q-2-0-2',
              question_text: 'Which key resets the view in TinkerCAD?',
              order_index: 2,
              quiz_options: [
                { id: 'seed-opt-2-0-2-0', option_text: 'F', is_correct: true },
                { id: 'seed-opt-2-0-2-1', option_text: 'R', is_correct: false },
                { id: 'seed-opt-2-0-2-2', option_text: 'V', is_correct: false },
                { id: 'seed-opt-2-0-2-3', option_text: 'Escape', is_correct: false },
              ],
            },
            {
              id: 'seed-q-2-0-3',
              question_text: 'How do you add a shape in TinkerCAD?',
              order_index: 3,
              quiz_options: [
                { id: 'seed-opt-2-0-3-0', option_text: 'Drag it from the right panel onto the workplane', is_correct: true },
                { id: 'seed-opt-2-0-3-1', option_text: 'Type the shape name in a command box', is_correct: false },
                { id: 'seed-opt-2-0-3-2', option_text: 'Draw it freehand with the mouse', is_correct: false },
                { id: 'seed-opt-2-0-3-3', option_text: 'Import it from a file', is_correct: false },
              ],
            },
          ],
        },
      },
      {
        title: 'Shapes, Holes & Grouping',
        estimated_minutes: 30,
        content_markdown: `## Shapes, Holes & Grouping\n\n### The Hole tool\nChange any shape to a **Hole** using the shape inspector on the right. When you group a hole with a solid shape, it subtracts the hole — like a cookie cutter.\n\n**Example:** Add a cylinder on top of a box → change cylinder to Hole → select both → press Ctrl+G → the cylinder cuts a hole through the box.\n\n### Grouping (Ctrl+G)\nGrouping combines shapes into one object. Always group when you're done editing a set of shapes together.\n\n### Aligning shapes\nSelect multiple shapes → click the Align button (or press L) → click the alignment dots to snap shapes to each other.\n\n### Keyboard shortcuts\n| Shortcut | Action |\n|----------|--------|\n| Ctrl+D | Duplicate |\n| Ctrl+G | Group |\n| Ctrl+Z | Undo |\n| Ctrl+C / Ctrl+V | Copy / Paste |`,
        videos: [{ title: 'TinkerCAD - Tutorial for Beginners in 10 MINS!', youtube_id: 'QIn9c5TjrKk', youtube_url: 'https://youtu.be/QIn9c5TjrKk' }],
        quiz: {
          id: 'seed-quiz-2-1',
          title: 'Shapes, Holes & Grouping',
          passing_score: 75,
          quiz_questions: [
            {
              id: 'seed-q-2-1-0',
              question_text: 'What happens when you group a Hole shape with a solid shape?',
              order_index: 0,
              quiz_options: [
                { id: 'seed-opt-2-1-0-0', option_text: 'The hole subtracts from the solid shape', is_correct: true },
                { id: 'seed-opt-2-1-0-1', option_text: 'The shapes merge into one larger shape', is_correct: false },
                { id: 'seed-opt-2-1-0-2', option_text: 'Both shapes disappear', is_correct: false },
                { id: 'seed-opt-2-1-0-3', option_text: 'The hole fills in with solid material', is_correct: false },
              ],
            },
            {
              id: 'seed-q-2-1-1',
              question_text: 'What keyboard shortcut groups shapes in TinkerCAD?',
              order_index: 1,
              quiz_options: [
                { id: 'seed-opt-2-1-1-0', option_text: 'Ctrl+G', is_correct: true },
                { id: 'seed-opt-2-1-1-1', option_text: 'Ctrl+D', is_correct: false },
                { id: 'seed-opt-2-1-1-2', option_text: 'Ctrl+Z', is_correct: false },
                { id: 'seed-opt-2-1-1-3', option_text: 'Ctrl+C', is_correct: false },
              ],
            },
            {
              id: 'seed-q-2-1-2',
              question_text: 'What does Ctrl+D do in TinkerCAD?',
              order_index: 2,
              quiz_options: [
                { id: 'seed-opt-2-1-2-0', option_text: 'Duplicate the selected shape', is_correct: true },
                { id: 'seed-opt-2-1-2-1', option_text: 'Delete the selected shape', is_correct: false },
                { id: 'seed-opt-2-1-2-2', option_text: 'Download the design', is_correct: false },
                { id: 'seed-opt-2-1-2-3', option_text: 'Deselect everything', is_correct: false },
              ],
            },
            {
              id: 'seed-q-2-1-3',
              question_text: 'How do you align shapes to each other in TinkerCAD?',
              order_index: 3,
              quiz_options: [
                { id: 'seed-opt-2-1-3-0', option_text: 'Select multiple shapes then click the Align button (or press L)', is_correct: true },
                { id: 'seed-opt-2-1-3-1', option_text: 'Drag them manually until they look even', is_correct: false },
                { id: 'seed-opt-2-1-3-2', option_text: 'Use Ctrl+A', is_correct: false },
                { id: 'seed-opt-2-1-3-3', option_text: 'Click the shape inspector', is_correct: false },
              ],
            },
          ],
        },
      },
      {
        title: 'Mini Project: Name Plate',
        estimated_minutes: 45,
        content_markdown: `## Mini Project: 3D Name Plate\n\nDesign a 3D name plate you can print and display!\n\n### Requirements\n- Base plate: at least 80mm wide × 30mm tall × 4mm thick\n- Your name in raised letters (at least 5mm tall)\n- Rounded corners (use the shape handles)\n- Optional: hole for hanging\n\n### Steps\n1. Add a Box: 80 × 30 × 4mm\n2. From the shape menu, find **Text** and drag it onto the workplane\n3. Type your name in the text panel\n4. Set text height to 5mm\n5. Position the text on top of the base plate (raise Z by 4mm)\n6. Select all → Group\n7. Save as "YourName_NamePlate_V1"\n\n### Export for printing\nClick Export → download as **.STL**`,
        videos: [],
        quiz: {
          id: 'seed-quiz-2-2',
          title: 'Name Plate Project',
          passing_score: 75,
          quiz_questions: [
            {
              id: 'seed-q-2-2-0',
              question_text: 'What is the minimum thickness for the name plate base?',
              order_index: 0,
              quiz_options: [
                { id: 'seed-opt-2-2-0-0', option_text: '4mm', is_correct: true },
                { id: 'seed-opt-2-2-0-1', option_text: '1mm', is_correct: false },
                { id: 'seed-opt-2-2-0-2', option_text: '10mm', is_correct: false },
                { id: 'seed-opt-2-2-0-3', option_text: '2mm', is_correct: false },
              ],
            },
            {
              id: 'seed-q-2-2-1',
              question_text: 'What is the minimum width for the name plate base?',
              order_index: 1,
              quiz_options: [
                { id: 'seed-opt-2-2-1-0', option_text: '80mm', is_correct: true },
                { id: 'seed-opt-2-2-1-1', option_text: '30mm', is_correct: false },
                { id: 'seed-opt-2-2-1-2', option_text: '10mm', is_correct: false },
                { id: 'seed-opt-2-2-1-3', option_text: '50mm', is_correct: false },
              ],
            },
            {
              id: 'seed-q-2-2-2',
              question_text: 'How do you export your TinkerCAD design for 3D printing?',
              order_index: 2,
              quiz_options: [
                { id: 'seed-opt-2-2-2-0', option_text: 'Click Export and download as .STL', is_correct: true },
                { id: 'seed-opt-2-2-2-1', option_text: 'Save as .PDF', is_correct: false },
                { id: 'seed-opt-2-2-2-2', option_text: 'Print directly from TinkerCAD', is_correct: false },
                { id: 'seed-opt-2-2-2-3', option_text: 'Export as .PNG image', is_correct: false },
              ],
            },
            {
              id: 'seed-q-2-2-3',
              question_text: 'How tall should the raised letter text be at minimum?',
              order_index: 3,
              quiz_options: [
                { id: 'seed-opt-2-2-3-0', option_text: '5mm', is_correct: true },
                { id: 'seed-opt-2-2-3-1', option_text: '1mm', is_correct: false },
                { id: 'seed-opt-2-2-3-2', option_text: '20mm', is_correct: false },
                { id: 'seed-opt-2-2-3-3', option_text: '0.5mm', is_correct: false },
              ],
            },
          ],
        },
      },
    ],
    homework: { title: 'Name Plate Redesign', description: 'Redesign your name plate with a decorative border, icon, or pattern. Save a screenshot and upload it here. Describe one thing you changed and why.', max_score: 10 },
  },
  {
    week_number: 3,
    title: 'Measurements & Precision',
    objectives: [
      'Set exact dimensions using the ruler tool',
      'Design objects to real-world measurements in mm',
      'Understand scale and replicate a physical object',
      'Design a printable ruler with embossed numbers',
    ],
    lessons: [
      {
        title: 'Precision Design in TinkerCAD',
        estimated_minutes: 25,
        content_markdown: `## Designing with Precision\n\nReal 3D printing is measured in **millimeters (mm)**. Getting dimensions right matters — especially for parts that need to fit together.\n\n### Setting exact dimensions\n1. Click a shape to select it\n2. Click the dimension labels that appear\n3. Type the exact value and press Enter\n\n### The Ruler tool\nEnable the ruler by clicking the ruler icon in the toolbar. This shows real measurements as you design.\n\n### Grid snapping\nBy default shapes snap to 1mm. For finer control: Edit Grid → set snap to 0.5mm or 0.1mm.\n\n### Exercise: Precision box\nCreate a box exactly **50mm × 30mm × 20mm** with **2mm walls** (use four thin boxes arranged as walls, grouped together).`,
        videos: [{ title: 'TinkerCAD - Tutorial for Beginners in 10 MINS!', youtube_id: 'QIn9c5TjrKk', youtube_url: 'https://youtu.be/QIn9c5TjrKk' }],
        quiz: {
          id: 'seed-quiz-3-0',
          title: 'Precision Design in TinkerCAD',
          passing_score: 75,
          quiz_questions: [
            {
              id: 'seed-q-3-0-0',
              question_text: 'What unit of measurement is used in 3D printing design?',
              order_index: 0,
              quiz_options: [
                { id: 'seed-opt-3-0-0-0', option_text: 'Millimeters (mm)', is_correct: true },
                { id: 'seed-opt-3-0-0-1', option_text: 'Inches', is_correct: false },
                { id: 'seed-opt-3-0-0-2', option_text: 'Centimeters', is_correct: false },
                { id: 'seed-opt-3-0-0-3', option_text: 'Meters', is_correct: false },
              ],
            },
            {
              id: 'seed-q-3-0-1',
              question_text: 'How do you set an exact dimension on a shape in TinkerCAD?',
              order_index: 1,
              quiz_options: [
                { id: 'seed-opt-3-0-1-0', option_text: 'Click the shape, click the dimension labels, and type the value', is_correct: true },
                { id: 'seed-opt-3-0-1-1', option_text: 'Draw the shape to the right size freehand', is_correct: false },
                { id: 'seed-opt-3-0-1-2', option_text: 'Use the color picker', is_correct: false },
                { id: 'seed-opt-3-0-1-3', option_text: 'Right-click and select "Set Size"', is_correct: false },
              ],
            },
            {
              id: 'seed-q-3-0-2',
              question_text: 'What is the default grid snap distance in TinkerCAD?',
              order_index: 2,
              quiz_options: [
                { id: 'seed-opt-3-0-2-0', option_text: '1mm', is_correct: true },
                { id: 'seed-opt-3-0-2-1', option_text: '0.1mm', is_correct: false },
                { id: 'seed-opt-3-0-2-2', option_text: '5mm', is_correct: false },
                { id: 'seed-opt-3-0-2-3', option_text: '10mm', is_correct: false },
              ],
            },
            {
              id: 'seed-q-3-0-3',
              question_text: 'Which tool shows real measurements as you design in TinkerCAD?',
              order_index: 3,
              quiz_options: [
                { id: 'seed-opt-3-0-3-0', option_text: 'The Ruler tool', is_correct: true },
                { id: 'seed-opt-3-0-3-1', option_text: 'The Grid tool', is_correct: false },
                { id: 'seed-opt-3-0-3-2', option_text: 'The Align tool', is_correct: false },
                { id: 'seed-opt-3-0-3-3', option_text: 'The Group tool', is_correct: false },
              ],
            },
          ],
        },
      },
      {
        title: 'Replicating Physical Objects',
        estimated_minutes: 35,
        content_markdown: `## Measuring & Replicating Real Objects\n\nA key design skill: measure something physical and recreate it digitally.\n\n### Tools you need\n- A ruler or measuring tape\n- Calipers (if you have them — they're very precise)\n\n### Exercise: Replicate an eraser\n1. Measure your eraser in mm (length × width × height)\n2. Write down the measurements\n3. In TinkerCAD, create a box with those exact dimensions\n4. Add your initials as embossed text on top\n\n### Why this matters\nWhen you design replacement parts, custom holders, or anything that needs to fit another object, you need to start from real measurements.`,
        videos: [],
        quiz: {
          id: 'seed-quiz-3-1',
          title: 'Replicating Physical Objects',
          passing_score: 75,
          quiz_questions: [
            {
              id: 'seed-q-3-1-0',
              question_text: 'Which tool gives the most precise measurements of a physical object?',
              order_index: 0,
              quiz_options: [
                { id: 'seed-opt-3-1-0-0', option_text: 'Calipers', is_correct: true },
                { id: 'seed-opt-3-1-0-1', option_text: 'A ruler', is_correct: false },
                { id: 'seed-opt-3-1-0-2', option_text: 'A tape measure', is_correct: false },
                { id: 'seed-opt-3-1-0-3', option_text: 'Estimating by eye', is_correct: false },
              ],
            },
            {
              id: 'seed-q-3-1-1',
              question_text: 'Why is replicating physical objects an important design skill?',
              order_index: 1,
              quiz_options: [
                { id: 'seed-opt-3-1-1-0', option_text: 'To design parts that fit other objects accurately', is_correct: true },
                { id: 'seed-opt-3-1-1-1', option_text: 'To make exact copies for selling', is_correct: false },
                { id: 'seed-opt-3-1-1-2', option_text: 'To avoid learning TinkerCAD', is_correct: false },
                { id: 'seed-opt-3-1-1-3', option_text: 'To skip the measuring step next time', is_correct: false },
              ],
            },
            {
              id: 'seed-q-3-1-2',
              question_text: 'What three dimensions do you need to measure for a box-shaped object?',
              order_index: 2,
              quiz_options: [
                { id: 'seed-opt-3-1-2-0', option_text: 'Length, width, and height', is_correct: true },
                { id: 'seed-opt-3-1-2-1', option_text: 'Color, weight, and texture', is_correct: false },
                { id: 'seed-opt-3-1-2-2', option_text: 'X, Y, and time', is_correct: false },
                { id: 'seed-opt-3-1-2-3', option_text: 'Diameter, radius, and area', is_correct: false },
              ],
            },
            {
              id: 'seed-q-3-1-3',
              question_text: 'In the eraser exercise, what do you add on top of the replicated shape?',
              order_index: 3,
              quiz_options: [
                { id: 'seed-opt-3-1-3-0', option_text: 'Your initials as embossed text', is_correct: true },
                { id: 'seed-opt-3-1-3-1', option_text: 'A hole for a keyring', is_correct: false },
                { id: 'seed-opt-3-1-3-2', option_text: 'A decorative border', is_correct: false },
                { id: 'seed-opt-3-1-3-3', option_text: 'A support structure', is_correct: false },
              ],
            },
          ],
        },
      },
    ],
    homework: { title: 'Measurement Sketches', description: 'Measure 3 household objects with a ruler. Sketch each one with labeled dimensions (length, width, height in mm). Upload a photo of your sketches. Choose one object to model in TinkerCAD next week.', max_score: 10 },
  },
  {
    week_number: 4,
    title: 'Keychains, Tags & Simple Tools',
    objectives: [
      'Apply shapes + holes + text for functional objects',
      'Export a correctly-oriented STL',
      'Design for printability (no overhangs over 45°)',
      'Print and hold your first custom-designed object',
    ],
    lessons: [
      {
        title: 'Design for Printability',
        estimated_minutes: 20,
        content_markdown: `## Design for Printability\n\nNot every 3D shape is easy to print. Here are the rules:\n\n### The 45° rule\nOverhangs greater than 45° from vertical need **supports** — extra plastic that holds them up during printing. Supports waste filament and can leave marks. Design to avoid them when possible.\n\n### Strong attachment holes\nFor a keychain ring, the hole must be:\n- At least **4mm diameter** for a key ring\n- Reinforced by walls at least 2mm thick around it\n- Printed with the flat face DOWN for strength\n\n### Layer direction matters\nLayers are like stacked cards — strong side-to-side, weaker when pulled apart. Orient your keychain so the longest axis is flat on the bed.`,
        videos: [],
        quiz: {
          id: 'seed-quiz-4-0',
          title: 'Design for Printability',
          passing_score: 75,
          quiz_questions: [
            {
              id: 'seed-q-4-0-0',
              question_text: 'What is the maximum overhang angle before you need supports?',
              order_index: 0,
              quiz_options: [
                { id: 'seed-opt-4-0-0-0', option_text: '45°', is_correct: true },
                { id: 'seed-opt-4-0-0-1', option_text: '90°', is_correct: false },
                { id: 'seed-opt-4-0-0-2', option_text: '30°', is_correct: false },
                { id: 'seed-opt-4-0-0-3', option_text: '60°', is_correct: false },
              ],
            },
            {
              id: 'seed-q-4-0-1',
              question_text: 'What is the minimum hole diameter for a keychain ring?',
              order_index: 1,
              quiz_options: [
                { id: 'seed-opt-4-0-1-0', option_text: '4mm', is_correct: true },
                { id: 'seed-opt-4-0-1-1', option_text: '1mm', is_correct: false },
                { id: 'seed-opt-4-0-1-2', option_text: '10mm', is_correct: false },
                { id: 'seed-opt-4-0-1-3', option_text: '2mm', is_correct: false },
              ],
            },
            {
              id: 'seed-q-4-0-2',
              question_text: 'In which direction are 3D printed layers the strongest?',
              order_index: 2,
              quiz_options: [
                { id: 'seed-opt-4-0-2-0', option_text: 'Side-to-side (horizontally)', is_correct: true },
                { id: 'seed-opt-4-0-2-1', option_text: 'Up-and-down (being pulled apart)', is_correct: false },
                { id: 'seed-opt-4-0-2-2', option_text: 'Diagonally', is_correct: false },
                { id: 'seed-opt-4-0-2-3', option_text: 'All directions equally', is_correct: false },
              ],
            },
            {
              id: 'seed-q-4-0-3',
              question_text: 'How thick should the walls around a keychain hole be?',
              order_index: 3,
              quiz_options: [
                { id: 'seed-opt-4-0-3-0', option_text: 'At least 2mm', is_correct: true },
                { id: 'seed-opt-4-0-3-1', option_text: 'At least 10mm', is_correct: false },
                { id: 'seed-opt-4-0-3-2', option_text: 'At least 0.1mm', is_correct: false },
                { id: 'seed-opt-4-0-3-3', option_text: 'Thickness does not matter', is_correct: false },
              ],
            },
          ],
        },
      },
      {
        title: 'Mini Project: Custom Keychain',
        estimated_minutes: 50,
        content_markdown: `## Design Your Custom Keychain\n\n### Requirements\n- Custom shape or silhouette (not just a rectangle)\n- Your initials, name, or a symbol\n- Attachment hole: at least 4mm diameter\n- Total size: 30–60mm\n- Minimum thickness: 4mm\n\n### Design ideas\n- Your favorite animal silhouette\n- A star, heart, or geometric shape with your initials\n- A tiny version of something you love\n\n### Steps\n1. Design your base shape (combine shapes or use a polygon)\n2. Add text or a symbol on the face\n3. Add the attachment hole (cylinder set to Hole, grouped with shape)\n4. Check: is the hole at least 4mm diameter?\n5. Export as STL\n6. **Print it!**\n\n### Cura settings for keychain\n- Layer height: 0.2mm\n- Infill: 30%\n- No supports needed if flat on bed`,
        videos: [{ title: 'TinkerCAD - Tutorial for Beginners in 10 MINS!', youtube_id: 'QIn9c5TjrKk', youtube_url: 'https://youtu.be/QIn9c5TjrKk' }],
        quiz: {
          id: 'seed-quiz-4-1',
          title: 'Custom Keychain',
          passing_score: 75,
          quiz_questions: [
            {
              id: 'seed-q-4-1-0',
              question_text: 'What is the minimum thickness for the keychain?',
              order_index: 0,
              quiz_options: [
                { id: 'seed-opt-4-1-0-0', option_text: '4mm', is_correct: true },
                { id: 'seed-opt-4-1-0-1', option_text: '1mm', is_correct: false },
                { id: 'seed-opt-4-1-0-2', option_text: '10mm', is_correct: false },
                { id: 'seed-opt-4-1-0-3', option_text: '8mm', is_correct: false },
              ],
            },
            {
              id: 'seed-q-4-1-1',
              question_text: 'What is the recommended total size range for the keychain?',
              order_index: 1,
              quiz_options: [
                { id: 'seed-opt-4-1-1-0', option_text: '30–60mm', is_correct: true },
                { id: 'seed-opt-4-1-1-1', option_text: '1–10mm', is_correct: false },
                { id: 'seed-opt-4-1-1-2', option_text: '100–200mm', is_correct: false },
                { id: 'seed-opt-4-1-1-3', option_text: '5–15mm', is_correct: false },
              ],
            },
            {
              id: 'seed-q-4-1-2',
              question_text: 'What infill percentage is recommended for the keychain in Cura?',
              order_index: 2,
              quiz_options: [
                { id: 'seed-opt-4-1-2-0', option_text: '30%', is_correct: true },
                { id: 'seed-opt-4-1-2-1', option_text: '5%', is_correct: false },
                { id: 'seed-opt-4-1-2-2', option_text: '80%', is_correct: false },
                { id: 'seed-opt-4-1-2-3', option_text: '100%', is_correct: false },
              ],
            },
            {
              id: 'seed-q-4-1-3',
              question_text: 'Why should the keychain be printed flat on the bed?',
              order_index: 3,
              quiz_options: [
                { id: 'seed-opt-4-1-3-0', option_text: 'For maximum strength and no supports needed', is_correct: true },
                { id: 'seed-opt-4-1-3-1', option_text: 'To use less filament', is_correct: false },
                { id: 'seed-opt-4-1-3-2', option_text: 'Because the printer requires it', is_correct: false },
                { id: 'seed-opt-4-1-3-3', option_text: 'To make it print faster', is_correct: false },
              ],
            },
          ],
        },
      },
    ],
    homework: { title: 'Desk Tool Concept', description: 'Think of a simple tool or helper you need at your desk (phone stand, cable clip, pen holder, etc.). Write a short description: Who is it for? What problem does it solve? How big should it be? Sketch it if you can.', max_score: 10 },
  },
  {
    week_number: 5,
    title: 'STL Files & Cura Slicing',
    objectives: [
      'Understand what an STL file is',
      'Install and use Cura slicer software',
      'Adjust layer height, infill, supports, and speed',
      'Generate and interpret a G-code print preview',
    ],
    lessons: [
      {
        title: 'What is an STL File?',
        estimated_minutes: 15,
        content_markdown: `## STL Files Explained\n\nAn **STL** (Standard Tessellation Language) file describes a 3D shape as a mesh of triangles. It's what TinkerCAD exports and what Cura reads.\n\n### STL → G-code pipeline\n\`\`\`\nTinkerCAD design → Export STL → Open in Cura → Slice → G-code → SD card → Printer\n\`\`\`\n\n### What is G-code?\nG-code is a list of movement instructions for your printer:\n- Move to X=10, Y=15\n- Heat nozzle to 200°C\n- Extrude 2.5mm of filament\n- etc.\n\nCura generates thousands of these lines automatically from your STL.`,
        videos: [],
        quiz: {
          id: 'seed-quiz-5-0',
          title: 'What is an STL File?',
          passing_score: 75,
          quiz_questions: [
            {
              id: 'seed-q-5-0-0',
              question_text: 'What does STL stand for?',
              order_index: 0,
              quiz_options: [
                { id: 'seed-opt-5-0-0-0', option_text: 'Standard Tessellation Language', is_correct: true },
                { id: 'seed-opt-5-0-0-1', option_text: 'Solid Triangle Layout', is_correct: false },
                { id: 'seed-opt-5-0-0-2', option_text: 'Simple Topology Layer', is_correct: false },
                { id: 'seed-opt-5-0-0-3', option_text: 'Standard Transfer Language', is_correct: false },
              ],
            },
            {
              id: 'seed-q-5-0-1',
              question_text: 'What does Cura convert an STL file into?',
              order_index: 1,
              quiz_options: [
                { id: 'seed-opt-5-0-1-0', option_text: 'G-code', is_correct: true },
                { id: 'seed-opt-5-0-1-1', option_text: 'PDF', is_correct: false },
                { id: 'seed-opt-5-0-1-2', option_text: 'JPEG', is_correct: false },
                { id: 'seed-opt-5-0-1-3', option_text: 'MP4', is_correct: false },
              ],
            },
            {
              id: 'seed-q-5-0-2',
              question_text: 'What is G-code?',
              order_index: 2,
              quiz_options: [
                { id: 'seed-opt-5-0-2-0', option_text: 'A list of movement instructions for the printer', is_correct: true },
                { id: 'seed-opt-5-0-2-1', option_text: 'A type of plastic filament', is_correct: false },
                { id: 'seed-opt-5-0-2-2', option_text: 'A 3D design software', is_correct: false },
                { id: 'seed-opt-5-0-2-3', option_text: 'A slicing file format', is_correct: false },
              ],
            },
            {
              id: 'seed-q-5-0-3',
              question_text: 'How does an STL file describe a 3D shape?',
              order_index: 3,
              quiz_options: [
                { id: 'seed-opt-5-0-3-0', option_text: 'As a mesh of triangles', is_correct: true },
                { id: 'seed-opt-5-0-3-1', option_text: 'As a list of colors', is_correct: false },
                { id: 'seed-opt-5-0-3-2', option_text: 'As a photograph', is_correct: false },
                { id: 'seed-opt-5-0-3-3', option_text: 'As a series of G-code layers', is_correct: false },
              ],
            },
          ],
        },
      },
      {
        title: 'Cura Slicing Walkthrough',
        estimated_minutes: 40,
        content_markdown: `## Using Cura\n\n### Install Cura\nDownload free from [ultimaker.com/software/ultimaker-cura](https://ultimaker.com/software/ultimaker-cura)\n\n### Add your printer\n1. Open Cura → Add Printer → Other → Creality Ender\n2. Select **Ender 2** (or Ender 2 Pro)\n\n### Key settings explained\n\n| Setting | What it does | Beginner value |\n|---------|-------------|----------------|\n| Layer Height | Thinner = smoother but slower | 0.2mm |\n| Infill % | How solid the inside is | 15–20% |\n| Print Speed | Faster = more risk of failure | 50mm/s |\n| Supports | Holds up overhangs | Enable if needed |\n| Build Plate Adhesion | Skirt/brim/raft | Brim for small parts |\n\n### Exercise\nSlice your Week 4 keychain at 3 settings and compare:\n- Draft: 0.3mm layers, 10% infill\n- Standard: 0.2mm, 15%\n- Fine: 0.15mm, 20%\n\nNote the estimated print time and file size for each.`,
        videos: [{ title: '3D Printing for ABSOLUTE Beginners: Step by Step Cura Tutorial', youtube_id: 'Px_pwZKif8I', youtube_url: 'https://youtu.be/Px_pwZKif8I' }],
        quiz: {
          id: 'seed-quiz-5-1',
          title: 'Cura Slicing',
          passing_score: 75,
          quiz_questions: [
            {
              id: 'seed-q-5-1-0',
              question_text: 'What layer height is recommended for a standard beginner print?',
              order_index: 0,
              quiz_options: [
                { id: 'seed-opt-5-1-0-0', option_text: '0.2mm', is_correct: true },
                { id: 'seed-opt-5-1-0-1', option_text: '5mm', is_correct: false },
                { id: 'seed-opt-5-1-0-2', option_text: '0.001mm', is_correct: false },
                { id: 'seed-opt-5-1-0-3', option_text: '2mm', is_correct: false },
              ],
            },
            {
              id: 'seed-q-5-1-1',
              question_text: 'What infill percentage is recommended for beginner prints?',
              order_index: 1,
              quiz_options: [
                { id: 'seed-opt-5-1-1-0', option_text: '15–20%', is_correct: true },
                { id: 'seed-opt-5-1-1-1', option_text: '100%', is_correct: false },
                { id: 'seed-opt-5-1-1-2', option_text: '1–2%', is_correct: false },
                { id: 'seed-opt-5-1-1-3', option_text: '50–60%', is_correct: false },
              ],
            },
            {
              id: 'seed-q-5-1-2',
              question_text: 'What does "Build Plate Adhesion: Brim" do?',
              order_index: 2,
              quiz_options: [
                { id: 'seed-opt-5-1-2-0', option_text: 'Adds extra material around the base to help small parts stick', is_correct: true },
                { id: 'seed-opt-5-1-2-1', option_text: 'Removes all adhesion settings', is_correct: false },
                { id: 'seed-opt-5-1-2-2', option_text: 'Increases print speed', is_correct: false },
                { id: 'seed-opt-5-1-2-3', option_text: 'Adds supports inside the model', is_correct: false },
              ],
            },
            {
              id: 'seed-q-5-1-3',
              question_text: 'What print speed is recommended for beginners?',
              order_index: 3,
              quiz_options: [
                { id: 'seed-opt-5-1-3-0', option_text: '50mm/s', is_correct: true },
                { id: 'seed-opt-5-1-3-1', option_text: '200mm/s', is_correct: false },
                { id: 'seed-opt-5-1-3-2', option_text: '5mm/s', is_correct: false },
                { id: 'seed-opt-5-1-3-3', option_text: '1000mm/s', is_correct: false },
              ],
            },
          ],
        },
      },
    ],
    homework: { title: 'Cura Settings Reference Card', description: 'Write down what each major Cura setting does IN YOUR OWN WORDS (layer height, infill, supports, print speed, bed adhesion). Upload a photo or typed document. Think of it as a cheat sheet for future you.', max_score: 10 },
  },
  {
    week_number: 6,
    title: 'Multi-Part Designs',
    objectives: [
      'Design an object with 2 or more printed parts',
      'Understand tolerance and fit (press fit vs. loose)',
      'Print and assemble a functional multi-part object',
      'Plan print orientation for each separate part',
    ],
    lessons: [
      {
        title: 'Tolerance & Fit',
        estimated_minutes: 25,
        content_markdown: `## Tolerance: Making Parts Fit Together\n\nWhen you print two parts that should fit together, you can't make them exactly the same size — the plastic needs a tiny gap to slide or snap together.\n\n### Tolerance guidelines (PLA on Ender)\n| Fit type | Gap to add |\n|----------|------------|\n| Loose/sliding fit | 0.4–0.6mm |\n| Press fit (snug) | 0.2–0.3mm |\n| Snap fit | 0.1–0.2mm |\n\n**Example:** If your box interior is 50mm wide, make the lid insert 49.4–49.8mm wide.\n\n### Test first!\nBefore printing your full design, print a small test piece to verify the fit. Save filament and time.`,
        videos: [],
        quiz: {
          id: 'seed-quiz-6-0',
          title: 'Tolerance & Fit',
          passing_score: 75,
          quiz_questions: [
            {
              id: 'seed-q-6-0-0',
              question_text: 'How much gap should you add for a loose/sliding fit between PLA parts?',
              order_index: 0,
              quiz_options: [
                { id: 'seed-opt-6-0-0-0', option_text: '0.4–0.6mm', is_correct: true },
                { id: 'seed-opt-6-0-0-1', option_text: '5–10mm', is_correct: false },
                { id: 'seed-opt-6-0-0-2', option_text: '0.001mm', is_correct: false },
                { id: 'seed-opt-6-0-0-3', option_text: '2–3mm', is_correct: false },
              ],
            },
            {
              id: 'seed-q-6-0-1',
              question_text: 'Which fit type requires the smallest tolerance gap?',
              order_index: 1,
              quiz_options: [
                { id: 'seed-opt-6-0-1-0', option_text: 'Snap fit (0.1–0.2mm)', is_correct: true },
                { id: 'seed-opt-6-0-1-1', option_text: 'Loose/sliding fit', is_correct: false },
                { id: 'seed-opt-6-0-1-2', option_text: 'Press fit', is_correct: false },
                { id: 'seed-opt-6-0-1-3', option_text: 'All fits require the same gap', is_correct: false },
              ],
            },
            {
              id: 'seed-q-6-0-2',
              question_text: 'Why should you print a small test piece before printing the full design?',
              order_index: 2,
              quiz_options: [
                { id: 'seed-opt-6-0-2-0', option_text: 'To verify the fit and save filament and time', is_correct: true },
                { id: 'seed-opt-6-0-2-1', option_text: 'Because the printer requires it', is_correct: false },
                { id: 'seed-opt-6-0-2-2', option_text: 'To use up extra filament', is_correct: false },
                { id: 'seed-opt-6-0-2-3', option_text: 'To check the color', is_correct: false },
              ],
            },
            {
              id: 'seed-q-6-0-3',
              question_text: 'If a box interior is 50mm wide, what width should the lid insert be for a press fit?',
              order_index: 3,
              quiz_options: [
                { id: 'seed-opt-6-0-3-0', option_text: '49.7–49.8mm', is_correct: true },
                { id: 'seed-opt-6-0-3-1', option_text: '50mm (exact)', is_correct: false },
                { id: 'seed-opt-6-0-3-2', option_text: '45mm', is_correct: false },
                { id: 'seed-opt-6-0-3-3', option_text: '55mm', is_correct: false },
              ],
            },
          ],
        },
      },
      {
        title: 'Project: 2-Part Pencil Holder',
        estimated_minutes: 60,
        content_markdown: `## Design a Pencil Holder with Removable Lid\n\n### Part 1: The body\n- Cylinder or box shape\n- Inside diameter: at least 60mm\n- Height: 100–120mm\n- Wall thickness: 3mm\n- No top (open)\n\n### Part 2: The lid\n- Matches the outer diameter of the body\n- Has a plug that fits inside the top opening (use your tolerance: body_inner_diameter - 0.4mm)\n- Optional: add a small lip or tab to lift it off\n\n### Print settings\n- Layer height: 0.2mm\n- Infill: 15% for body, 20% for lid\n- No supports needed if walls are vertical\n- Print body upside down (open end up) for best quality\n\n### Assemble and test\nDoes the lid fit? Too tight? Too loose? Note it for next time.`,
        videos: [],
        quiz: {
          id: 'seed-quiz-6-1',
          title: '2-Part Pencil Holder',
          passing_score: 75,
          quiz_questions: [
            {
              id: 'seed-q-6-1-0',
              question_text: 'What is the minimum inside diameter for the pencil holder body?',
              order_index: 0,
              quiz_options: [
                { id: 'seed-opt-6-1-0-0', option_text: '60mm', is_correct: true },
                { id: 'seed-opt-6-1-0-1', option_text: '10mm', is_correct: false },
                { id: 'seed-opt-6-1-0-2', option_text: '200mm', is_correct: false },
                { id: 'seed-opt-6-1-0-3', option_text: '30mm', is_correct: false },
              ],
            },
            {
              id: 'seed-q-6-1-1',
              question_text: 'How thick should the pencil holder walls be?',
              order_index: 1,
              quiz_options: [
                { id: 'seed-opt-6-1-1-0', option_text: '3mm', is_correct: true },
                { id: 'seed-opt-6-1-1-1', option_text: '0.1mm', is_correct: false },
                { id: 'seed-opt-6-1-1-2', option_text: '20mm', is_correct: false },
                { id: 'seed-opt-6-1-1-3', option_text: '1mm', is_correct: false },
              ],
            },
            {
              id: 'seed-q-6-1-2',
              question_text: 'Why should the body be printed upside down (open end up)?',
              order_index: 2,
              quiz_options: [
                { id: 'seed-opt-6-1-2-0', option_text: 'For best quality on the open rim', is_correct: true },
                { id: 'seed-opt-6-1-2-1', option_text: 'Because the printer requires it', is_correct: false },
                { id: 'seed-opt-6-1-2-2', option_text: 'To use less filament', is_correct: false },
                { id: 'seed-opt-6-1-2-3', option_text: 'To make it print faster', is_correct: false },
              ],
            },
            {
              id: 'seed-q-6-1-3',
              question_text: 'How do you calculate the lid plug width for a good fit?',
              order_index: 3,
              quiz_options: [
                { id: 'seed-opt-6-1-3-0', option_text: 'Body inner diameter minus 0.4mm', is_correct: true },
                { id: 'seed-opt-6-1-3-1', option_text: 'Body outer diameter plus 2mm', is_correct: false },
                { id: 'seed-opt-6-1-3-2', option_text: 'Body inner diameter plus 5mm', is_correct: false },
                { id: 'seed-opt-6-1-3-3', option_text: 'Body inner diameter times 2', is_correct: false },
              ],
            },
          ],
        },
      },
    ],
    homework: { title: 'Final Project Sketch', description: 'Sketch your Week 8 capstone project idea. Describe: Who is the user? What problem does it solve? How many parts will it have? What size is it? Upload your sketch and description.', max_score: 10 },
  },
  {
    week_number: 7,
    title: 'Product Design Challenge',
    objectives: [
      'Apply design thinking: Empathize → Define → Ideate → Prototype → Test',
      'Create a prototype, test it, and iterate',
      'Document the design process with notes and photos',
      'Give and receive constructive feedback',
    ],
    lessons: [
      {
        title: 'Design Thinking Process',
        estimated_minutes: 30,
        content_markdown: `## Design Thinking\n\nDesign thinking is a 5-step process used by professional product designers at companies like Apple, IDEO, and Nike.\n\n### The 5 steps\n\n1. **Empathize** — Understand the person who will use your product. What do they struggle with? Interview them.\n\n2. **Define** — Write a clear problem statement: *"[User] needs a way to [goal] because [reason]."*\n\n3. **Ideate** — Sketch at least 3 different ideas. No bad ideas at this stage! Quantity over quality.\n\n4. **Prototype** — Build the most promising idea. It doesn't need to be perfect — just testable.\n\n5. **Test** — Show it to real users. Ask: Does this solve the problem? What would you change?\n\n### This week\nInterview a family member about a daily frustration. Design something that helps them.`,
        videos: [],
        quiz: {
          id: 'seed-quiz-7-0',
          title: 'Design Thinking Process',
          passing_score: 75,
          quiz_questions: [
            {
              id: 'seed-q-7-0-0',
              question_text: 'What are the 5 steps of design thinking in the correct order?',
              order_index: 0,
              quiz_options: [
                { id: 'seed-opt-7-0-0-0', option_text: 'Empathize, Define, Ideate, Prototype, Test', is_correct: true },
                { id: 'seed-opt-7-0-0-1', option_text: 'Sketch, Design, Print, Test, Ship', is_correct: false },
                { id: 'seed-opt-7-0-0-2', option_text: 'Measure, Plan, Build, Evaluate, Repeat', is_correct: false },
                { id: 'seed-opt-7-0-0-3', option_text: 'Research, Prototype, Test, Launch, Iterate', is_correct: false },
              ],
            },
            {
              id: 'seed-q-7-0-1',
              question_text: 'What is the goal of the "Ideate" step?',
              order_index: 1,
              quiz_options: [
                { id: 'seed-opt-7-0-1-0', option_text: 'Generate many different ideas without judging them', is_correct: true },
                { id: 'seed-opt-7-0-1-1', option_text: 'Build the final product', is_correct: false },
                { id: 'seed-opt-7-0-1-2', option_text: 'Interview the user', is_correct: false },
                { id: 'seed-opt-7-0-1-3', option_text: 'Test with real users', is_correct: false },
              ],
            },
            {
              id: 'seed-q-7-0-2',
              question_text: 'What should a good problem statement include?',
              order_index: 2,
              quiz_options: [
                { id: 'seed-opt-7-0-2-0', option_text: 'The user, their goal, and the reason', is_correct: true },
                { id: 'seed-opt-7-0-2-1', option_text: 'The solution, the cost, and the timeline', is_correct: false },
                { id: 'seed-opt-7-0-2-2', option_text: 'The color, size, and material', is_correct: false },
                { id: 'seed-opt-7-0-2-3', option_text: 'The brand, the logo, and the price', is_correct: false },
              ],
            },
            {
              id: 'seed-q-7-0-3',
              question_text: 'What is the main purpose of a prototype?',
              order_index: 3,
              quiz_options: [
                { id: 'seed-opt-7-0-3-0', option_text: 'To create something testable', is_correct: true },
                { id: 'seed-opt-7-0-3-1', option_text: 'To create the perfect final product', is_correct: false },
                { id: 'seed-opt-7-0-3-2', option_text: 'To show to investors', is_correct: false },
                { id: 'seed-opt-7-0-3-3', option_text: 'To skip the testing step', is_correct: false },
              ],
            },
          ],
        },
      },
      {
        title: 'Build & Test Your Prototype',
        estimated_minutes: 90,
        content_markdown: `## Prototype → Print → Test → Improve\n\n### Your design brief template\n\`\`\`\nUser: [who]\nProblem: [what frustrates them]\nSolution idea: [your concept]\nParts needed: [list]\nSize constraints: [dimensions]\n\`\`\`\n\n### Print V1\nDon't aim for perfect. Aim for *testable*. A rough first version you can hold and evaluate is worth 10 perfect designs on screen.\n\n### Collect feedback\nAsk 3 questions:\n1. Does this solve the problem?\n2. What's awkward or uncomfortable about it?\n3. What's one thing you'd change?\n\n### Design V2\nBased on feedback, make one or two targeted improvements in TinkerCAD. Save as V2.`,
        videos: [],
        quiz: {
          id: 'seed-quiz-7-1',
          title: 'Build & Test Your Prototype',
          passing_score: 75,
          quiz_questions: [
            {
              id: 'seed-q-7-1-0',
              question_text: 'How many feedback questions should you ask when testing your prototype?',
              order_index: 0,
              quiz_options: [
                { id: 'seed-opt-7-1-0-0', option_text: '3', is_correct: true },
                { id: 'seed-opt-7-1-0-1', option_text: '10', is_correct: false },
                { id: 'seed-opt-7-1-0-2', option_text: '1', is_correct: false },
                { id: 'seed-opt-7-1-0-3', option_text: '20', is_correct: false },
              ],
            },
            {
              id: 'seed-q-7-1-1',
              question_text: 'What should be your goal when printing Version 1 (V1)?',
              order_index: 1,
              quiz_options: [
                { id: 'seed-opt-7-1-1-0', option_text: 'Create something testable, not perfect', is_correct: true },
                { id: 'seed-opt-7-1-1-1', option_text: 'Make a perfect finished product', is_correct: false },
                { id: 'seed-opt-7-1-1-2', option_text: 'Use as much filament as possible', is_correct: false },
                { id: 'seed-opt-7-1-1-3', option_text: 'Avoid collecting any feedback', is_correct: false },
              ],
            },
            {
              id: 'seed-q-7-1-2',
              question_text: 'What is the purpose of Version 2 (V2)?',
              order_index: 2,
              quiz_options: [
                { id: 'seed-opt-7-1-2-0', option_text: 'Apply targeted improvements based on feedback', is_correct: true },
                { id: 'seed-opt-7-1-2-1', option_text: 'Start the design completely from scratch', is_correct: false },
                { id: 'seed-opt-7-1-2-2', option_text: 'Add more colors', is_correct: false },
                { id: 'seed-opt-7-1-2-3', option_text: 'Make it significantly bigger', is_correct: false },
              ],
            },
            {
              id: 'seed-q-7-1-3',
              question_text: 'Which of these belongs in a design brief?',
              order_index: 3,
              quiz_options: [
                { id: 'seed-opt-7-1-3-0', option_text: 'User, problem, solution idea, parts needed, size constraints', is_correct: true },
                { id: 'seed-opt-7-1-3-1', option_text: 'Color preferences, font choices, logo design', is_correct: false },
                { id: 'seed-opt-7-1-3-2', option_text: 'Printer brand, filament brand, slicer version', is_correct: false },
                { id: 'seed-opt-7-1-3-3', option_text: 'Delivery date, customer name, order number', is_correct: false },
              ],
            },
          ],
        },
      },
    ],
    homework: { title: 'V2 Design File', description: 'Submit your V2 TinkerCAD design (screenshot or exported STL). Describe what feedback you received on V1 and what specific changes you made for V2.', max_score: 10 },
  },
  {
    week_number: 8,
    title: 'Final Capstone Project',
    objectives: [
      'Complete a polished, multi-part 3D printed object',
      'Demonstrate the full idea → design → print → improve workflow',
      'Present your project and explain your decisions',
      'Reflect on your learning over the summer',
    ],
    lessons: [
      {
        title: 'Finalize & Print Your Capstone',
        estimated_minutes: 120,
        content_markdown: `## Capstone Project Week!\n\nThis is your showcase. Put everything you've learned into one great project.\n\n### Requirements\n- At least **3 distinct printed parts** that assemble together\n- Solves a **real problem** for a real person\n- Includes **V1 and V2** (you iterated at least once)\n- Print quality is your best yet\n\n### Final checklist\n- [ ] All parts designed in TinkerCAD\n- [ ] STL files exported and sliced\n- [ ] All parts printed and assembled\n- [ ] Project photographed from multiple angles\n- [ ] Design brief written\n- [ ] Reflection written\n\n### Presentation (verbal or written)\nExplain:\n1. Who is it for and what problem does it solve?\n2. What decisions did you make and why?\n3. What did you learn?\n4. What would you do differently?`,
        videos: [],
        quiz: {
          id: 'seed-quiz-8-0',
          title: 'Capstone Project',
          passing_score: 75,
          quiz_questions: [
            {
              id: 'seed-q-8-0-0',
              question_text: 'How many distinct printed parts does the capstone project require at minimum?',
              order_index: 0,
              quiz_options: [
                { id: 'seed-opt-8-0-0-0', option_text: '3', is_correct: true },
                { id: 'seed-opt-8-0-0-1', option_text: '1', is_correct: false },
                { id: 'seed-opt-8-0-0-2', option_text: '10', is_correct: false },
                { id: 'seed-opt-8-0-0-3', option_text: '2', is_correct: false },
              ],
            },
            {
              id: 'seed-q-8-0-1',
              question_text: 'What does "you iterated" mean for the capstone?',
              order_index: 1,
              quiz_options: [
                { id: 'seed-opt-8-0-1-0', option_text: 'You created V1, got feedback, and improved it to V2', is_correct: true },
                { id: 'seed-opt-8-0-1-1', option_text: 'You printed the same design multiple times', is_correct: false },
                { id: 'seed-opt-8-0-1-2', option_text: 'You used multiple colors of filament', is_correct: false },
                { id: 'seed-opt-8-0-1-3', option_text: 'You designed without TinkerCAD', is_correct: false },
              ],
            },
            {
              id: 'seed-q-8-0-2',
              question_text: 'What should your capstone project solve?',
              order_index: 2,
              quiz_options: [
                { id: 'seed-opt-8-0-2-0', option_text: 'A real problem for a real person', is_correct: true },
                { id: 'seed-opt-8-0-2-1', option_text: 'A math equation', is_correct: false },
                { id: 'seed-opt-8-0-2-2', option_text: 'A puzzle or game', is_correct: false },
                { id: 'seed-opt-8-0-2-3', option_text: 'A coding challenge', is_correct: false },
              ],
            },
            {
              id: 'seed-q-8-0-3',
              question_text: 'When presenting your project, which of these should you explain?',
              order_index: 3,
              quiz_options: [
                { id: 'seed-opt-8-0-3-0', option_text: 'Who it is for, decisions made, and what you learned', is_correct: true },
                { id: 'seed-opt-8-0-3-1', option_text: 'The cost of the filament only', is_correct: false },
                { id: 'seed-opt-8-0-3-2', option_text: 'How long it took to print', is_correct: false },
                { id: 'seed-opt-8-0-3-3', option_text: 'The exact G-code settings used', is_correct: false },
              ],
            },
          ],
        },
      },
    ],
    homework: { title: 'Reflection Essay', description: 'Write 1 page (or record a short video) reflecting on your summer: What did you learn? What was hardest? What are you most proud of? What do you want to make next? Upload your essay and project photos.', max_score: 10 },
  },
]
